version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
      - echo "Listing contents of the current directory:"
      - ls -la
      - if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; else echo "requirements.txt not found"; fi
  pre_build:
    commands:
      - echo "Pre-build phase started"
      #- pip3 install awscli
  build:
    commands:
      - echo "Build phase started"
      #- zip -r lambda_function.zip .
  post_build:
    commands:
      - echo "Build phase completed"
      #- ls -la  # List directory contents after build
      - zip -q -x  *.git* -r artifact.zip .
      - aws lambda update-function-code --region=us-east-1 --function-name github-to-lambda-demo --zip-file fileb://artifact.zip
      - aws lambda wait function-updated --function-name github-to-lambda-demo
      - aws lambda get-function --function-name github-to-lambda-demo --query 'Configuration.[State, LastUpdateStatus]'
      - newVersion=$(aws lambda publish-version --region=us-east-1 --function-name github-to-lambda-demo --query Version --output text)
      - currentVersion=$(aws lambda get-alias --region=us-east-1 --function-name github-to-lambda-demo --name production --query FunctionVersion --output text)
      - echo "phase completed"
     
